export PATH=$PATH:~/dotfiles/bin
export ZSH=~/.oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom/plugins
export EDITOR=vim
export ZSH_THEME=looneym
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=xterm-256color
export KEYTIMEOUT=1

source $ZSH/oh-my-zsh.sh
ZSH_THEME="looneym"
plugins=(
  git
)
autoload -U compinit && compinit
source $ZSH_CUSTOM/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH_CUSTOM/zsh-autosuggestions/zsh-autosuggestions.zsh

source ~/.transient
source ~/.aliases
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.linuxbrew/bin/brew  ] && eval $(~/.linuxbrew/bin/brew shellenv) 
[ -f ~/dotfiles/conf/local.conf  ] && source ~/dotfiles/conf/local.conf  
