export ZSH=~/.oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom/plugins
export EDITOR=vim
export ZSH_THEME=looneym
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=screen-256color
export KEYTIMEOUT=1
export PRETTYUSER="looneym"

source $ZSH/oh-my-zsh.sh
ZSH_THEME="looneym"

zstyle ':completion:*' list-prompt   ''
zstyle ':completion:*' select-prompt ''
plugins=(
  git
  fzf-tab
)
autoload -U compinit && compinit
source $ZSH_CUSTOM/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH_CUSTOM/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source $(which assume-role)
source ~/.transient
source ~/.aliases
# eval "$(intercom-profile)"
export PATH=~/dotfiles/bin:$PATH


BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"
