#!/bin/bash

# meta
ar() {
  echo "Reloading .zshrc"
  source ~/.zshrc
}

ae() {
  vim ~/.aliases
  ar
}

aa() {
  a="alias $1=\"$(lc)\""
  echo $a >>~/.aliases
  echo "Added new alias: $a"
  ar
}
alias aliasadd="add_alias"
alias lc="history | tail -n 1 | cut -c 8-"

alias te='vim ~/.transient'
alias ze='vim ~/.zshrc'
alias se="vim ~/.ssh/config"
alias zs='source ~/.zshrc && echo Succesfully reloaded .zshrc! 🎉'

# What's my ip?
alias eip='curl ipinfo.io/ip'
alias iip="ipconfig getifaddr en0"

alias src="cd ~/src"
alias x="chmod +x"
alias ops='eval $(op signin intercom)'
alias wideboi="tmux new -A -s wideboi"
alias skinnyboi="tmux new -A -s skinnyboi"
alias p="peco"

# Git
function git() { hub $@; }
alias gb="git branch"
alias gca="git commit --amend --no-edit"
alias gcae="git commit --amend"
alias gcm="git commit"
alias gco="git checkout"
alias gd="git difftool"
alias gdm="echo 'Comparing changes against origin/master' &&git difftool origin/master"
alias gfa="git fetch --all"
alias glo="git log --oneline"
alias gs="git status"
alias gc="git commit -m "
alias gpub="git publish | grep 'pull/new' | awk '{ print $2 }' | pbcopy && echo 'Link copied to clipboard'"
alias gzoom="gco master && git pull"
alias gzoom!="git stash && gco master && git pull"
# TODO: move this to gitconfig
alias noop="git checkout master && git pull && git checkout -b ml/noop && git commit --allow-empty -m \"noop\""

# Manage PRs
cmsg() {
  cat .git/COMMIT_EDITMSG | grep -v '^#'
}

pro() {
  hub pull-request --no-edit
}

proe() {
  hub pull-request -m "$(cmsg)" --edit
}

prls() {
  hub pr list -h $(git branch-name)
}

# Docker
nuke_docker() {
  # Delete all containers
  docker stop $(docker ps -a -q)
  docker rm -f $(docker ps -a -q)
  # Delete all images
  docker rmi $(docker images -q)
  docker system prune
}

ds() {
  # TODO
  # - override entrypoint?
  if [[ -z "$1" ]]; then
    shell="/bin/bash"
  else
    shell="/bin/$1"
  fi

  artifact=$(echo "containers\nimages" | peco)

  if [[ "$artifact" == "containers" ]]; then
    docker exec -it $(docker ps | peco | awk '{print $1}') "$shell"
  elif [[ "$artifact" == "images" ]]; then
    docker run -it $(docker images | peco | awk '{print $3}') "$shell"
  fi
}

dimg() {
  docker images "*$1*" --format "{{.ID}}"
}

# Clipboard
clip() {
  echo $1 | nc localhost 8377
}

tc() {
  input=""
  while read line; do input+="$line \n"; done
  echo $input | tmux load-buffer -
  echo $input | nc localhost 8377
}

gsha() {
  glo $1 | peco | awk '{print $1}'
}

man() {
  vim -c "runtime! ftplugin/man.vim" -c "let g:ft_man_open_mode = 'tab'" -c ":Man $1" -c "tabonly"
}

rcd() {
  cd ~/src/$(ls ~/src/ | peco)
}

re() {
  cd ~/src/$(ls ~/src/ | peco)
  vim -c ':NERDTreeToggle'
}

mkscript() {
  script=$1
  touch $script
  echo " #!/usr/bin/env bash" >$script
  chmod +x $script
}

function role() {
  account=$(jq -r 'keys[]' ~/.aws/accounts | peco)
  assume-role $account team-dev-infra $(botp)
}

rr() {
  fc "$(history | sort -rn | peco | awk '{print $1}')"
}

symlinks_help() {
  cat <<EndOfMessage
  paths=".zshrc .vimrc .tmux.conf .gitconfig .gitignore.global .aliases .git_template"
  for path in \$paths; do
    echo "Creating symlink to \$path in home directory."
    ln -sf ~/dotfiles/\$path ~/\$path
  done
EndOfMessage
}

col() {
  cut -d " " -f$1
}
