#! /usr/bin/env bash

set -euo pipefail

usage() {
  echo "install OPTIONS"
  echo
  echo "Options:"
  echo "  -l Lite install: do not install brew or any packages "
  echo "  -p PLATFORM operating system you are working on"
  echo "     available platforms:"
  echo "       - mac"
  echo "       - arch"
  echo "       - al2 (amazon linux 2)"
}

parse_options() {
  export LITE_INSTALL="false"
  while getopts ":lp:" opt; do
    case ${opt} in
    l)
      export LITE_INSTALL="true"
      ;;
    p)
      export PLATFORM=$OPTARG
      ;;
    \?)
      usage
      exit
      ;;
    esac
  done
  set +u
  [ -z "$PLATFORM" ] && usage && exit
  set -u
}

run_modules() {
  lib/install/base_packages
  lib/install/brew
  lib/install/zsh
  lib/install/symlinks
  lib/install/create_local_conf
}

parse_options "$@"
run_modules
