#! /usr/bin/env bash

set -euo pipefail

usage() {
  echo "install OPTIONS"
  echo
  echo "Options:"
  echo "  -l Lite install: do not install brew or any packages "
}

parse_options() {

  export LITE_INSTALL="false"
  while getopts ":l" opt; do
    case ${opt} in
    l)
      export LITE_INSTALL="true"
      ;;
    \?)
      usage
      exit
      ;;
    esac
  done
}

detect_platform() {
  if uname -a | grep -q amzn2; then
    export PLATFORM="al2"
  elif uname -a | grep -q Darwin; then
    export PLATFORM="mac"
  elif uname -a | grep -q arch; then
    export PLATFORM="arch"
  fi
}

run_modules() {
  lib/install/base_packages
  lib/install/brew
  lib/install/zsh
  lib/install/symlinks
  lib/install/clipper
  lib/install/create_local_conf
}

parse_options "$@"
detect_platform
run_modules
