#! /usr/bin/env bash

install_homebrew() {
  if [[ "$PLATFORM" == "mac" ]]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  elif [[ "$PLATFORM" == "al2" || "$PLATFORM" == "arch" ]]; then
    if [ ! -d ~/.linuxbrew/Homebrew ]; then
      git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
    fi
    mkdir -p ~/.linuxbrew/bin
    ln -sf ../Homebrew/bin/brew ~/.linuxbrew/bin
    eval $(~/.linuxbrew/bin/brew shellenv)
  fi
}

taps() {
  brew tap drone/drone
}

install_brew_packages() {
  declare -a brew_packages=(
    # "ag"
    # "cmake"
    # "ctags"
    # "drone"
    # "entr"
    # "hub"
    # "python"
    # "shfmt"
    # "tmux"
    # "vim"
    "zsh"
  )
  brew install "${brew_packages[@]}"
}

if [ "$LITE_INSTALL" == "true" ]; then
  echo "lite install only"
  exit 0
else
  install_homebrew
  taps
  install_brew_packages
fi
