#! /usr/bin/env bash


install_homebrew() {
	if [ "$PLATFORM" == "mac" ]; then
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi
}

install_brew_packages() {
  declare -a brew_packages=(
  "ag"
  "cmake"
  "ctags"
  "entr"
  "hub"
  "openssh"
  "shfmt"
  "tmux"
  "vim"
  "zsh"
  )
 brew install "${brew_packages[@]}"
}

install_assume_role(){
  brew tap coinbase/assume-role
  brew install assume-role
}

install_homebrew
install_brew_packages
install_assume_role
