#! /usr/bin/env bash

create_symlinks() {
  paths="zshrc vimrc tmux.conf gitconfig gitignore.global aliases git_template"
  for path in $paths; do
    echo "Creating symlink to $path in home directory."
    ln -sf ~/dotfiles/dotfiles/$path ~/.$path
  done

  touch ~/.transient
  ln -sf ~/dotfiles/themes/looneym.zsh-theme ~/.oh-my-zsh/themes/looneym.zsh-theme
}

create_symlinks
